### ISSUE TITLE
모듈 구성

### ISSUE THREAD

**Issue by isprogrammingfun** [KUSITMS-29th-TEAM-B/Backend#2]
## 💡 Issue
멀티모듈 구성 

## 📝 todo
- [x] domain 모듈 생성 
- [x] infrastructure 모듈 생성
- [x] common 모듈 생성
