### ISSUE TITLE
회원가입, 로그인 코드 리팩터링

### ISSUE THREAD

**Issue by isprogrammingfun** [KUSITMS-29th-TEAM-B/Backend#35]
## 💡 Issue

회원가입, 로그인 관련 리팩터링

## 📝 todo

- [x] 회원가입 입력 값들에 대한 검증 추가
- [x] 로그인 API 코드 리팩터링
- [x] 프로필 이미지 url 조회 API 개발
