### ISSUE TITLE
JD 등록, 자소서 등록 API 구현

### ISSUE THREAD

**Issue by isprogrammingfun** [KUSITMS-29th-TEAM-B/Backend#56]
## 💡 Issue

JD 등록 API 구현
자소서 등록 API 구현

## 📝 todo

- [ ] JD 등록 API 구현
- [ ] JD 등록 API 테스트 코드 작성
- [ ] 관련 로직들 단위 테스트 코드 작성
- [ ] 자소서 등록 API 구현
- [ ] 자소서 등록 API 테스트 코드 작성
- [ ] 관련 로직들 단위 테스트 코드 작성
