### ISSUE TITLE
CI/CD 환경 구축

### ISSUE THREAD

**Issue by whereami2048** [KUSITMS-29th-TEAM-B/Backend#7]
## 💡 Issue
CI/CD 환경 구축

## 📝 todo
- [x]  ec2, rds 생성
- [x] 도커,도커 컴포즈, nginx 설치
- [x] swap 메모리 설정
- [x] 도커 파일 작성
- [x] deploy.sh 작성
- [x] workflow 파일 작성
