### ISSUE TITLE
JD 수정, 삭제 API 구현

### ISSUE THREAD

**Issue by isprogrammingfun** [KUSITMS-29th-TEAM-B/Backend#86]
## 💡 Issue

JD 수정 API 구현
JD 삭제 API 구현

## 📝 todo

- [x] JD 수정 API 구현
- [x] JD 삭제 API 구현
- [x] 테스트 코드 작성
